-- CreateTable
CREATE TABLE "StudioMember" (
    "slug" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "role" JSONB NOT NULL,
    "description" JSONB NOT NULL,
    "bio" JSONB NOT NULL,
    "model" TEXT NOT NULL,
    "scale" DOUBLE PRECISION NOT NULL,
    "roughness" DOUBLE PRECISION NOT NULL,
    "metalness" DOUBLE PRECISION NOT NULL,
    "hair" TEXT,
    "rotation" DOUBLE PRECISION[],
    "highlight" TEXT NOT NULL,
    "socials" JSONB NOT NULL,
    "labels" JSONB NOT NULL,
    "projects" TEXT[],
    "suite" BOOLEAN NOT NULL DEFAULT false,
    "facts" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "StudioMember_pkey" PRIMARY KEY ("slug")
);

-- CreateIndex
CREATE UNIQUE INDEX "StudioMember_position_key" ON "StudioMember"("position");

-- the members that lived in apps/client/app/[locale]/studio/studio.json
INSERT INTO "StudioMember" ("slug", "position", "name", "role", "description", "bio", "model", "scale", "roughness", "metalness", "hair", "rotation", "highlight", "socials", "labels", "projects", "suite", "facts", "updatedAt") VALUES
('fanga', 0, 'Fanga', '{"en": "Developer", "fr": "Développeur", "es": "Desarrollador", "de": "Entwickler"}'::jsonb, '{"en": "Fanga is our mastermind. He constantly upgrades our working stack, and makes our jobs the easiest it gets. His current task is to build the Facile Suite. (Yes all by himself)", "fr": "Fanga, c''est notre cerveau. Il améliore sans cesse notre stack et nous rend le travail aussi facile que possible. Sa mission du moment : construire la Facile Suite. (Oui, tout seul)", "es": "Fanga es nuestro cerebro. Mejora sin parar nuestro stack de trabajo y nos hace el día a día lo más fácil posible. Su misión actual: construir la Facile Suite. (Sí, él solo)", "de": "Fanga ist unser Mastermind. Er verbessert ständig unseren Tech-Stack und macht uns die Arbeit so leicht wie möglich. Seine aktuelle Aufgabe: die Facile Suite bauen. (Ja, ganz allein)"}'::jsonb, '{"en": "Placeholder long bio for Fanga — replace via the backoffice. Full-stack developer at Facile Studio, most at home in the backend and the infrastructure under it: services, pipelines, and the tooling that keeps the rest of the studio moving.", "fr": "Bio longue provisoire pour Fanga, à remplacer via le backoffice. Développeur full-stack chez Facile Studio, surtout à l''aise dans le backend et l''infrastructure qui le porte : services, pipelines et l''outillage qui fait avancer le reste du studio.", "es": "Biografía larga provisional de Fanga, sustitúyela desde el backoffice. Desarrollador full-stack en Facile Studio, en su salsa en el backend y en la infraestructura que lo sostiene: servicios, pipelines y las herramientas que mantienen al resto del estudio en marcha.", "de": "Platzhalter für Fangas ausführliche Bio, bitte im Backoffice ersetzen. Full-Stack-Entwickler bei Facile Studio, am liebsten im Backend und in der Infrastruktur darunter: Services, Pipelines und die Tools, die den Rest des Studios am Laufen halten."}'::jsonb, '/models/fanga.glb', 0.015, 0.85, 1.0, '#6E5A4E', ARRAY[0.0, 0.6732, -0.4]::double precision[], '#29A863', '[{"label": "LinkedIn", "href": "https://linkedin.com/in/thevyann"}, {"label": "GitHub", "href": "https://www.github.com/saravenpi"}]'::jsonb, '{"en": ["Backend", "Infra", "Tooling"], "fr": ["Backend", "Infra", "Outillage"], "es": ["Backend", "Infra", "Herramientas"], "de": ["Backend", "Infra", "Tooling"]}'::jsonb, ARRAY['marcel', 'projet-zero', 'benky', 'muse']::text[], true, '{"en": ["Listens to 10 hours of Wii music while working", "Never backs down from a hard mission, always gives his fullest"], "fr": ["Écoute 10 heures de musique Wii en travaillant", "Ne recule jamais devant une mission difficile, et donne toujours tout"], "es": ["Escucha 10 horas de música de Wii mientras trabaja", "Nunca se echa atrás ante una misión difícil, siempre lo da todo"], "de": ["Hört bei der Arbeit 10 Stunden Wii-Musik", "Scheut keine schwierige Mission und gibt immer alles"]}'::jsonb, CURRENT_TIMESTAMP),
('noah', 1, 'Noah', '{"en": "Designer", "fr": "Designer", "es": "Diseñador", "de": "Designer"}'::jsonb, '{"en": "Noah is the web designer and frontend developer. He learned UI | UX as an autodidact and uses his skills to craft beautiful websites", "fr": "Noah est le web designer et développeur frontend. Il a appris l''UI | UX en autodidacte et s''en sert pour créer de beaux sites web", "es": "Noah es el diseñador web y desarrollador frontend. Aprendió UI | UX de forma autodidacta y usa lo que sabe para crear webs preciosas", "de": "Noah ist Webdesigner und Frontend-Entwickler. UI | UX hat er sich selbst beigebracht, und damit gestaltet er wunderschöne Websites"}'::jsonb, '{"en": "He specialises in creating sleek designs and implementing them with attractive and unique GSAP animations.", "fr": "Sa spécialité : des designs épurés, mis en mouvement par des animations GSAP uniques et séduisantes.", "es": "Se especializa en crear diseños elegantes y darles vida con animaciones GSAP atractivas y únicas.", "de": "Er ist spezialisiert auf elegante Designs, die er mit ansprechenden, einzigartigen GSAP-Animationen umsetzt."}'::jsonb, '/models/noah.glb', 0.015, 0.85, 1.0, '#6E5A4E', ARRAY[0.0, 0.6732, -0.4]::double precision[], '#2C9CCC', '[{"label": "Dribbble", "href": "https://www.dribbble.com/webbygian"}, {"label": "GitHub", "href": "https://www.github.com/G1anC"}, {"label": "Instagram", "href": "https://www.instagram.com/webbygian"}]'::jsonb, '{"en": ["UI | UX systems", "Animations", "Frontend"], "fr": ["Systèmes UI | UX", "Animations", "Frontend"], "es": ["Sistemas UI | UX", "Animaciones", "Frontend"], "de": ["UI | UX-Systeme", "Animationen", "Frontend"]}'::jsonb, ARRAY['marcel', 'hottake', 'laura-herve', 'projet-zero', 'evelynecrea', 'handvision', 'muse']::text[], false, '{"en": ["Constantly changing his Linux setup"], "fr": ["Change sans arrêt sa config Linux"], "es": ["Siempre está cambiando su configuración de Linux"], "de": ["Baut ständig sein Linux-Setup um"]}'::jsonb, CURRENT_TIMESTAMP),
('mazouz', 2, 'Mazouz', '{"en": "Developer", "fr": "Développeur", "es": "Desarrollador", "de": "Entwickler"}'::jsonb, '{"en": "Mazouz is a literal swiss knife. Any task you give him, he''ll do. Creating web apps and taking care of the hardest features are two of his countless skills.", "fr": "Mazouz est un vrai couteau suisse. Quelle que soit la tâche, il s''en charge. Créer des applications web et venir à bout des fonctionnalités les plus coriaces font partie de ses innombrables talents.", "es": "Mazouz es una auténtica navaja suiza. Dale cualquier tarea y la hará. Crear apps web y encargarse de las funcionalidades más difíciles son solo dos de sus incontables habilidades.", "de": "Mazouz ist ein echtes Schweizer Taschenmesser. Egal welche Aufgabe, er erledigt sie. Web-Apps bauen und die kniffligsten Features stemmen sind nur zwei seiner unzähligen Fähigkeiten."}'::jsonb, '{"en": "Placeholder long bio for Mazouz — replace via the backoffice. Developer at Facile Studio, on the backend side: APIs, data, and the automation that removes the work nobody wants to do twice.", "fr": "Bio longue provisoire pour Mazouz, à remplacer via le backoffice. Développeur chez Facile Studio, côté backend : API, données et l''automatisation qui supprime le travail que personne ne veut faire deux fois.", "es": "Biografía larga provisional de Mazouz, sustitúyela desde el backoffice. Desarrollador en Facile Studio, del lado del backend: APIs, datos y la automatización que elimina el trabajo que nadie quiere hacer dos veces.", "de": "Platzhalter für Mazouz'' ausführliche Bio, bitte im Backoffice ersetzen. Entwickler bei Facile Studio, im Backend: APIs, Daten und die Automatisierung, die Arbeit abschafft, die niemand zweimal machen will."}'::jsonb, '/models/mazouz.glb', 4.5, 0.85, 1.0, '#6E5A4E', ARRAY[0.0, 0.6732, -0.4]::double precision[], '#CF6322', '[{"label": "GitHub", "href": "https://www.github.com/MezzLMC"}]'::jsonb, '{"en": ["Backend", "APIs", "Data", "Automation"], "fr": ["Backend", "API", "Données", "Automatisation"], "es": ["Backend", "APIs", "Datos", "Automatización"], "de": ["Backend", "APIs", "Daten", "Automatisierung"]}'::jsonb, ARRAY['hottake', 'marcel', 'evelynecrea', 'vidoq', 'muse']::text[], false, '{"en": ["Currently learning to cook", "Sees coding as his sanctuary", "loves hearing people''s stories", "nothing beats a Sunday afternoon side quest"], "fr": ["Apprend à cuisiner en ce moment", "Voit le code comme son sanctuaire", "adore écouter les histoires des gens", "rien ne vaut une quête secondaire un dimanche après-midi"], "es": ["Ahora mismo está aprendiendo a cocinar", "Ve la programación como su santuario", "le encanta escuchar las historias de la gente", "nada supera una misión secundaria un domingo por la tarde"], "de": ["Lernt gerade kochen", "Programmieren ist sein Rückzugsort", "hört gern die Geschichten anderer Menschen", "nichts geht über eine Nebenquest am Sonntagnachmittag"]}'::jsonb, CURRENT_TIMESTAMP),
('camille', 3, 'Camille', '{"en": "Designer", "fr": "Designer", "es": "Diseñadora", "de": "Designerin"}'::jsonb, '{"en": "Camille is our design director. Coming from graphic design studies and a photography background. She has a keen eye to make everything beautiful", "fr": "Camille est notre directrice artistique. Passée par des études de graphisme et venue de la photographie, elle a l''œil pour rendre tout plus beau", "es": "Camille es nuestra directora de diseño. Estudió diseño gráfico, viene del mundo de la fotografía y tiene buen ojo para que todo quede bonito", "de": "Camille ist unsere Design-Direktorin. Sie hat Grafikdesign studiert, kommt aus der Fotografie und hat ein feines Gespür dafür, alles schön zu machen"}'::jsonb, '{"en": "Placeholder long bio for Camille — replace via the backoffice. Designer at Facile Studio, working on brand, illustration and print: the art direction that gives a project its voice before a single line is written.", "fr": "Bio longue provisoire pour Camille, à remplacer via le backoffice. Designer chez Facile Studio, entre marque, illustration et print : la direction artistique qui donne sa voix à un projet avant qu''une seule ligne soit écrite.", "es": "Biografía larga provisional de Camille, sustitúyela desde el backoffice. Diseñadora en Facile Studio, entre marca, ilustración e impresión: la dirección de arte que da voz a un proyecto antes de escribir una sola línea.", "de": "Platzhalter für Camilles ausführliche Bio, bitte im Backoffice ersetzen. Designerin bei Facile Studio, zuständig für Marke, Illustration und Print: die Art Direction, die einem Projekt seine Stimme gibt, bevor auch nur eine Zeile geschrieben ist."}'::jsonb, '/models/camille.glb', 0.015, 0.85, 1.0, NULL, ARRAY[0.0, 0.6732, -0.4]::double precision[], '#9E3CE9', '[{"label": "Instagram", "href": "https://www.instagram.com/camg_raphic/"}]'::jsonb, '{"en": ["Branding", "graphical chart", "design direction"], "fr": ["Branding", "charte graphique", "direction artistique"], "es": ["Branding", "guía de estilo", "dirección de diseño"], "de": ["Branding", "Styleguide", "Art Direction"]}'::jsonb, ARRAY['projet-zero', 'hottake', 'marcel', 'muse']::text[], false, '{"en": ["Loves getting into her bubble to read her romance books", "Our sun — keeps everyone motivated with a giant smile"], "fr": ["Adore se mettre dans sa bulle pour lire ses romans d''amour", "Notre soleil : elle motive tout le monde avec un sourire immense"], "es": ["Le encanta meterse en su burbuja a leer novelas románticas", "Nuestro sol: nos mantiene motivados con una sonrisa enorme"], "de": ["Zieht sich gern in ihre eigene Welt zurück, um Liebesromane zu lesen", "Unser Sonnenschein: motiviert alle mit einem riesigen Lächeln"]}'::jsonb, CURRENT_TIMESTAMP);
